//
//  ChartPublicGlobalKeys.m
//  ChartDome
//
//  Created by 索晓晓 on 15/12/7.
//  Copyright © 2015年 索晓晓. All rights reserved.
//

#import "ChartPublicGlobalKeys.h"
/**小表格的文字颜色*/
NSString *const CHART_OPTION_CELL_COLOR = @"CHART_OPTION_CELL_COLOR";
/**小表格的背景颜色*/
NSString *const CHART_OPTION_CELL_BACKGROUND = @"CHART_OPTION_CELL_BACKGROUND";
/**小表格的边框颜色*/
NSString *const CHART_OPTION_CELL_BOARDCOLOR = @"CHART_OPTION_CELL_BOARDCOLOR";
/**小表格的边框宽度*/
NSString *const CHART_OPTION_CELL_BOARDWIDTH = @"CHART_OPTION_CELL_BOARDWIDTH";
/**小表格的文字大小*/
NSString *const CHART_OPTION_CELL_FONT = @"CHART_OPTION_CELL_FONT";
/**cell 的点击颜色*/
NSString *const CHART_OPTION_CELL_SELECTEDCOLOR = @"CHART_OPTION_CELL_SELECTEDCOLOR";
/**表格的头部文字大小*/
NSString *const CHART_OPTION_CHARTHEADER_FONT = @"CHART_OPTION_CHARTHEADER_FONT";
/**表格的头部文字颜色*/
NSString *const CHART_OPTION_CHARTHEADER_COLOR = @"CHART_OPTION_CHARTHEADER_COLOR";
/**表格的头部视图的背景颜色*/
NSString *const CHART_OPTION_CHARTHEADER_BACKGROUND = @"CHART_OPTION_CHARTHEADER_BACKGROUND";
/**cell 的第一列文字颜色*/
NSString *const CHART_OPTION_FIRST_CELL_COLOT = @"CHART_OPTION_FIRST_CELL_COLOT";
/**cell奇数行背景颜色隔行*/
NSString *const CHART_OPTION_ODDNUM_BACKGROUND = @"CHART_OPTION_ODDNUM_BACKGROUND";
/** cell key*/
NSString *const CHART_OPTION_TABLEVIEW_ID = @"CHART_OPTION_TABLEVIEW_ID";
/**cell 的高度*/
NSString *const CHART_OPTION_CELL_HEIGHT = @"CHART_OPTION_CELL_HEIGHT";
/**表格头部的高度*/
NSString *const CHART_OPTION_CHARTHEADER_HEIGHT = @"CHART_OPTION_CHARTHEADER_HEIGHT";
/** headerKey */
NSString *const CHART_OPTION_TABLEVIEW_HEADER_ID = @"CHART_OPTION_TABLEVIEW_HEADER_ID";

/**cell偶数行背景颜色隔行*/
NSString *const CHART_OPTION_EVENNUM_BACKGROUND = @"CHART_OPTION_EVENNUM_BACKGROUND";

/**tableView背景颜色*/
NSString *const CHART_OPTION_TABLEVIEW_BACKGROUND = @"CHART_OPTION_TABLEVIEW_BACKGROUND";


@implementation ChartPublicGlobalKeys

@end
